---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-glusterfs
spec:
  storageClassName: glusterfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-glusterfs 
spec:
  selector:
    matchLabels:
      app: nginx-glusterfs 
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-glusterfs
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /mnt
          name: pvc-data
      volumes:
      - name: pvc-data
        persistentVolumeClaim:
          claimName: pvc-glusterfs 
          readOnly: false
